# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Your Website Title"
first_name: "Jong-Min"
middle_name: "R."
last_name: "Moon"
description: "A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design."
footer_text: "Powered by <a href='https://jekyllrb.com/' target='_blank'>Jekyll</a> with <a href='https://github.com/alshedivat/al-folio'>al-folio</a> theme."
keywords: "jekyll, jekyll-theme, academic-website, portfolio-website" 
lang: en 
icon: "⚛️" 
url: "https://jong-min-moon.github.io" 
baseurl: "" 
last_updated: false 
back_to_top: true 

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-toc # Required for {% toc %} tag
  - jekyll-github-metadata

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: 
  - "_pages"
exclude:
  - "bin/"
  - "CONTRIBUTING.md"
  - "CUSTOMIZE.md"
  - "Dockerfile"
  - "docker-compose.yml"
  - "docker-compose-slim.yml"
  - "FAQ.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "INSTALL.md"
  - "LICENSE"
  - "lighthouse_results/"
  - "package.json"
  - "package-lock.json"
  - "purgecss.config.js"
  - "README.md"
  - "readme_preview/"
  - "vendor"
keep_files:
  - "CNAME"
  - ".nojekyll"
